#!/usr/bin/make
#
# makefile for SPECTRE on Macbook (64-bit) with Intel inside 
#
################################################################################
#===================  USER MAY HAVE TO CHANGE PATHS ===========================#
#====> Compilers and Flags
CC = cc

# using gfotran-snwleo-intel-bin.tar.gz from http://hpc.sourceforge.net/
F77 = /usr/local/bin/gfortran -std=legacy

FC = /usr/local/bin/gfortran -Wall-O0  -Wnonstd-intrinsics 
FFLAGS = -c -O0 -fsecond-underscore
#
# NOTE:something in the gcc -m64 compilation of supermongo produced
#      libraries with a two-underscore default which cannot be read
#      by SPECTRE unless compiled here with a second underscore
#
LFLAGS =  -Wall -O0 -Wsurprising,--defsym,mem_=0 -fbounds-check

#====> Libraries and Flags
# the following line points to the X11 libraries
HOSTLIBS = -lm 
FITLIB = -Bdynamic /usr/X11R6/lib/libX11.dylib \
	-L/usr/lib -ldevices -lplotsub -lutils



X11LIB = /usr/lib64
SMLIB = /uufs/astro.utah.edu/sys/pkg/sm/std/lib

#
# NOTE: must compile supermongo as 64-bit for the new macs
#

#===================  USER MAY HAVE TO CHANGE PATHS ===========================#
################################################################################


# Object files for creating SPECTRE
OBJECTS = Average.o Blank.o Blowbox.o Blowx.o Blowy.o Charith.o \
          Comtalk.o Const.o Cont.o Contin.o Correl.o Cosbell.o Crays.o \
          Cross.o Dark.o Deconv.o Detrm4.o Dex.o Dishead.o Divide.o \
          Dskfil.o Dump.o Edit.o Eight.o Elines.o Estim.o Expblow.o \
          Fft.o Findtic.o Fillist.o Findmin.o Findcont.o Flatcont.o \
          Flip.o Fourpn.o Fourpt.o Fracton.o Fts.o Gauss.o Getasci.o \
          Getcom.o Getline.o Getnum.o Gfill.o Glitch.o Hit.o Hunt.o \
          H2omake.o Interp.o Killf.o Labset.o Logit.o Lsd.o Manual.o \
          Merge.o Minimax.o Mkgauss.o Mkline.o Move.o Mrklin.o Nansi.o \
          Newcont.o Noise.o Number.o Paperpl.o Parab.o Peek.o Pfill.o \
          Pfilt.o Pick.o Plotxy.o Plus.o Positon.o Prdata.o Prinfo.o \
          Printh.o Putasci.o Puterr.o Quit.o Readcf.o Rebin.o Reed.new.o \
          Record.o Remove.o Remzero.o Rescal.o Rnorm.o Rtext.o Save.redhat.o \
          Savecf.o Scale.o Sclbgn.o Screenstat.o Setcont.o Setplt.o \
          Setre.o Shuffle.o Simp.o Sine.o Single.o Solve.o Sort.o \
          Spectre.o Splint.o Splitds.o Spln.o Splnc.o Startup.redhat.o \
          Stext.o Switch.o Syminv.o Taucalc.o Tellur.o Tilt.o Title.o \
          Velocity.o Velset.o Voigtcal.o Voigtfit.o Wave.o Wavelst.o \
          Which.o Width.o Yshift.o Zoom.o Zot.o \
	  Multicmd.o Cropstr.o\
	  Setav.o Changelinelist.o Plotlines.o

# Common variables to be included in subroutines
COMMON =  Chars.com Datachr.com Dataval.com Mathval.com Plotchr.com \
          Plotval.com Scrnval.com Widpar.com 





# The compilation and linking commands
all: SPECTRE;
	@echo ----------------------------------------------
	@echo Make sure you have the correct path to the 
	@echo code within the Spectre.f file
	@echo ----------------------------------------------
	@echo
	@echo
 
 
# RULES:
.SUFFIXES: .o .f
.f.o:
	$(F77) $(FFLAGS) $<

SPECTRE:  $(OBJECTS);
	$(FC) $(OBJECTS) -o SPECTRE \
	$(HOSTLIBS) $(FITLIB)
 
$(OBJECTS): $(COMMON)
 
clean:
	-rm -f *.o SPECTRE libSPECTRE.a

